namespace SexyFramework.Graphics;

public enum SEXY3DTEXTURETRANSFORMFLAGS
{
	SEXY3DTTFF_DISABLE = 0,
	SEXY3DTTFF_COUNT1 = 1,
	SEXY3DTTFF_COUNT2 = 2,
	SEXY3DTTFF_COUNT3 = 3,
	SEXY3DTTFF_COUNT4 = 4,
	SEXY3DTTFF_PROJECTED = 256,
	SEXY3DTTFF_FORCE_DWORD = int.MaxValue
}
