namespace SexyFramework.Graphics;

public enum SEXY3DSAMPLERSTATETYPE
{
	SEXY3DSAMP_ADDRESSU = 1,
	SEXY3DSAMP_ADDRESSV = 2,
	SEXY3DSAMP_ADDRESSW = 3,
	SEXY3DSAMP_BORDERCOLOR = 4,
	SEXY3DSAMP_MAGFILTER = 5,
	SEXY3DSAMP_MINFILTER = 6,
	SEXY3DSAMP_MIPFILTER = 7,
	SEXY3DSAMP_MIPMAPLODBIAS = 8,
	SEXY3DSAMP_MAXMIPLEVEL = 9,
	SEXY3DSAMP_MAXANISOTROPY = 10,
	SEXY3DSAMP_SRGBTEXTURE = 11,
	SEXY3DSAMP_ELEMENTINDEX = 12,
	SEXY3DSAMP_DMAPOFFSET = 13,
	SEXY3DSAMP_FORCE_DWORD = int.MaxValue
}
