namespace SexyFramework.Graphics;

public enum SEXY3DTEXTUREADDRESS
{
	SEXY3DTADDRESS_WRAP = 1,
	SEXY3DTADDRESS_MIRROR = 2,
	SEXY3DTADDRESS_CLAMP = 3,
	SEXY3DTADDRESS_BORDER = 4,
	SEXY3DTADDRESS_MIRRORONCE = 5,
	SEXY3DTADDRESS_FORCE_DWORD = int.MaxValue
}
