namespace SexyFramework.Graphics;

public enum SEXY3DBLENDMODE
{
	SEXY3DBLEND_ZERO = 1,
	SEXY3DBLEND_ONE = 2,
	SEXY3DBLEND_SRCCOLOR = 3,
	SEXY3DBLEND_INVSRCCOLOR = 4,
	SEXY3DBLEND_SRCALPHA = 5,
	SEXY3DBLEND_INVSRCALPHA = 6,
	SEXY3DBLEND_DESTALPHA = 7,
	SEXY3DBLEND_INVDESTALPHA = 8,
	SEXY3DBLEND_DESTCOLOR = 9,
	SEXY3DBLEND_INVDESTCOLOR = 10,
	SEXY3DBLEND_SRCALPHASAT = 11,
	SEXY3DBLEND_BOTHSRCALPHA = 12,
	SEXY3DBLEND_BOTHINVSRCALPHA = 13,
	SEXY3DBLEND_BLENDFACTOR = 14,
	SEXY3DBLEND_INVBLENDFACTOR = 15,
	SEXY3DBLEND_FORCE_DWORD = int.MaxValue
}
