namespace SexyFramework.Graphics;

public enum SEXY3DTEXTUREOP
{
	SEXY3DTOP_DISABLE = 1,
	SEXY3DTOP_SELECTARG1 = 2,
	SEXY3DTOP_SELECTARG2 = 3,
	SEXY3DTOP_MODULATE = 4,
	SEXY3DTOP_MODULATE2X = 5,
	SEXY3DTOP_MODULATE4X = 6,
	SEXY3DTOP_ADD = 7,
	SEXY3DTOP_ADDSIGNED = 8,
	SEXY3DTOP_ADDSIGNED2X = 9,
	SEXY3DTOP_SUBTRACT = 10,
	SEXY3DTOP_ADDSMOOTH = 11,
	SEXY3DTOP_BLENDDIFFUSEALPHA = 12,
	SEXY3DTOP_BLENDTEXTUREALPHA = 13,
	SEXY3DTOP_BLENDFACTORALPHA = 14,
	SEXY3DTOP_BLENDTEXTUREALPHAPM = 15,
	SEXY3DTOP_BLENDCURRENTALPHA = 16,
	SEXY3DTOP_PREMODULATE = 17,
	SEXY3DTOP_MODULATEALPHA_ADDCOLOR = 18,
	SEXY3DTOP_MODULATECOLOR_ADDALPHA = 19,
	SEXY3DTOP_MODULATEINVALPHA_ADDCOLOR = 20,
	SEXY3DTOP_MODULATEINVCOLOR_ADDALPHA = 21,
	SEXY3DTOP_BUMPENVMAP = 22,
	SEXY3DTOP_BUMPENVMAPLUMINANCE = 23,
	SEXY3DTOP_DOTPRODUCT3 = 24,
	SEXY3DTOP_MULTIPLYADD = 25,
	SEXY3DTOP_LERP = 26,
	SEXY3DTOP_FORCE_DWORD = int.MaxValue
}
