namespace SexyFramework.Graphics;

public enum SEXY3DTEXTUREFILTERTYPE
{
	SEXY3DTEXF_NONE = 0,
	SEXY3DTEXF_POINT = 1,
	SEXY3DTEXF_LINEAR = 2,
	SEXY3DTEXF_ANISOTROPIC = 3,
	SEXY3DTEXF_PYRAMIDALQUAD = 6,
	SEXY3DTEXF_GAUSSIANQUAD = 7,
	SEXY3DTEXF_FORCE_DWORD = int.MaxValue
}
