namespace SexyFramework.Graphics;

public enum SEXY3DSTENCILOP
{
	SEXY3DSTENCILOP_KEEP = 1,
	SEXY3DSTENCILOP_ZERO = 2,
	SEXY3DSTENCILOP_REPLACE = 3,
	SEXY3DSTENCILOP_INCRSAT = 4,
	SEXY3DSTENCILOP_DECRSAT = 5,
	SEXY3DSTENCILOP_INVERT = 6,
	SEXY3DSTENCILOP_INCR = 7,
	SEXY3DSTENCILOP_DECR = 8,
	SEXY3DSTENCILOP_FORCE_DWORD = int.MaxValue
}
