namespace SexyFramework.Graphics;

public enum SEXY3DCMPFUNC
{
	SEXY3DCMP_NEVER = 1,
	SEXY3DCMP_LESS = 2,
	SEXY3DCMP_EQUAL = 3,
	SEXY3DCMP_LESSEQUAL = 4,
	SEXY3DCMP_GREATER = 5,
	SEXY3DCMP_NOTEQUAL = 6,
	SEXY3DCMP_GREATEREQUAL = 7,
	SEXY3DCMP_ALWAYS = 8,
	SEXY3DCMP_FORCE_DWORD = int.MaxValue
}
