namespace SexyFramework.Graphics;

public enum SEXY3DCUBEMAP_FACES
{
	SEXY3DCUBEMAP_FACE_POSITIVE_X = 0,
	SEXY3DCUBEMAP_FACE_NEGATIVE_X = 1,
	SEXY3DCUBEMAP_FACE_POSITIVE_Y = 2,
	SEXY3DCUBEMAP_FACE_NEGATIVE_Y = 3,
	SEXY3DCUBEMAP_FACE_POSITIVE_Z = 4,
	SEXY3DCUBEMAP_FACE_NEGATIVE_Z = 5,
	SEXY3DCUBEMAP_FACE_FORCE_DWORD = int.MaxValue
}
