namespace SexyFramework.Graphics;

public enum SEXY3DTEXTURESTAGESTATETYPE
{
	SEXY3DTSS_COLOROP = 1,
	SEXY3DTSS_COLORARG1 = 2,
	SEXY3DTSS_COLORARG2 = 3,
	SEXY3DTSS_ALPHAOP = 4,
	SEXY3DTSS_ALPHAARG1 = 5,
	SEXY3DTSS_ALPHAARG2 = 6,
	SEXY3DTSS_BUMPENVMAT00 = 7,
	SEXY3DTSS_BUMPENVMAT01 = 8,
	SEXY3DTSS_BUMPENVMAT10 = 9,
	SEXY3DTSS_BUMPENVMAT11 = 10,
	SEXY3DTSS_TEXCOORDINDEX = 11,
	SEXY3DTSS_BUMPENVLSCALE = 22,
	SEXY3DTSS_BUMPENVLOFFSET = 23,
	SEXY3DTSS_TEXTURETRANSFORMFLAGS = 24,
	SEXY3DTSS_COLORARG0 = 26,
	SEXY3DTSS_ALPHAARG0 = 27,
	SEXY3DTSS_RESULTARG = 28,
	SEXY3DTSS_CONSTANT = 32,
	SEXY3DTSS_FORCE_DWORD = int.MaxValue
}
