namespace SexyFramework.Graphics;

public enum SEXY3DBLENDOP
{
	SEXY3DBLENDOP_ADD = 1,
	SEXY3DBLENDOP_SUBTRACT = 2,
	SEXY3DBLENDOP_REVSUBTRACT = 3,
	SEXY3DBLENDOP_MIN = 4,
	SEXY3DBLENDOP_MAX = 5,
	SEXY3DBLENDOP_FORCE_DWORD = int.MaxValue
}
