namespace SexyFramework.Graphics;

public enum SEXY3DPRIMITIVETYPE
{
	SEXY3DPT_POINTLIST = 1,
	SEXY3DPT_LINELIST = 2,
	SEXY3DPT_LINESTRIP = 3,
	SEXY3DPT_TRIANGLELIST = 4,
	SEXY3DPT_TRIANGLESTRIP = 5,
	SEXY3DPT_TRIANGLEFAN = 6,
	SEXY3DPT_FORCE_DWORD = int.MaxValue
}
