<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>SexyFramework</AssemblyName>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <GenerateTargetFrameworkAttribute>False</GenerateTargetFrameworkAttribute>
    <TargetFramework>net10.0-android</TargetFramework>
    <SupportedOSPlatformVersion>21.0</SupportedOSPlatformVersion>
    <Nullable>disable</Nullable>
  </PropertyGroup>
  <PropertyGroup>
    <LangVersion>12.0</LangVersion>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <CheckForOverflowUnderflow>False</CheckForOverflowUnderflow>
    <NoWarn>$(NoWarn);CA1416</NoWarn>
  </PropertyGroup>
  <PropertyGroup>
    <RootNamespace>SexyFrameworkAndroid</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <None Remove="Microsoft.Xna.Framework.RuntimeProfile" />
    <EmbeddedResource Include="Microsoft.Xna.Framework.RuntimeProfile" LogicalName="Microsoft.Xna.Framework.RuntimeProfile" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="MonoGame.Framework.Android" Version="3.8.4.1" />
  </ItemGroup>
</Project>
