namespace SexyFramework;

public enum MessageBoxFlags
{
	MSGBOX_OK = 0,
	MSGBOX_OKCANCEL = 1,
	MSGBOX_ABORTRETRYIGNORE = 2,
	MSGBOX_YESNOCANCEL = 3,
	MSGBOX_YESNO = 4,
	MSGBOX_RETRYCANCEL = 5,
	MSGBOX_CANCELTRYCONTINUE = 6,
	MSGBOX_ICONERROR = 16,
	MSGBOX_ICONQUESTION = 32,
	MSGBOX_ICONWARNING = 48,
	MSGBOX_ICONINFORMATION = 64
}
