namespace SexyFramework;

public enum MessageBoxResults
{
	MSGBOX_RESULT_OK = 1,
	MSGBOX_RESULT_CANCEL = 2,
	MSGBOX_RESULT_ABORT = 3,
	MSGBOX_RESULT_RETRY = 4,
	MSGBOX_RESULT_IGNORE = 5,
	MSGBOX_RESULT_YES = 6,
	MSGBOX_RESULT_NO = 7,
	MSGBOX_RESULT_TRYAGAIN = 10,
	MSGBOX_RESULT_CONTINUE = 11
}
